# Generated by Django 3.2.8 on 2021-11-02 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='statusdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('UnderProcess', 'UnderProcess'), ('Returned', 'Returned')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200, null=True)),
                ('producttype', models.CharField(choices=[('ACER', 'ACER'), ('DELL', 'DELL'), ('HP', 'HP'), ('SAMSUNG', 'SAMSUNG'), ('LENOVO', 'LENOVO'), ('MACBOOK', 'MACBOOK'), ('MI NOTEBOOK', 'MI NOTEBOOK'), ('ASUS', 'ASUS')], default='laptop', max_length=100)),
                ('serialnumber', models.CharField(max_length=200, null=True)),
                ('Date_Of_Purchase', models.DateField(blank=True, null=True, verbose_name='Date_Of_Purchase(dd/mm/yyyy)')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
